// <auto-generated />
using System;
using Api.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Shared.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924132033_ImageResults")]
    partial class ImageResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Modules.Image.ImageResultRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CnnElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("cnn_elapsed_ms");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("findings");

                    b.Property<string>("Issues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issues");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("LlmElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("llm_elapsed_ms");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("Pneumonia")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pneumonia");

                    b.Property<bool?>("PneumoniaPositive")
                        .HasColumnType("boolean")
                        .HasColumnName("pneumonia_positive");

                    b.Property<double?>("PneumoniaProbability")
                        .HasColumnType("double precision")
                        .HasColumnName("pneumonia_probability");

                    b.Property<int>("PositiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("positive_count");

                    b.Property<string>("Report")
                        .HasColumnType("jsonb")
                        .HasColumnName("report");

                    b.Property<string>("ReportAttempt")
                        .HasColumnType("jsonb")
                        .HasColumnName("report_attempt");

                    b.Property<bool>("ValidationPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("validation_passed");

                    b.HasKey("Id")
                        .HasName("pk_image_results");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_image_results_job_id");

                    b.ToTable("image_results", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Text.Experiments.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Combos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("combos");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocCount")
                        .HasColumnType("integer")
                        .HasColumnName("doc_count");

                    b.Property<string>("Environment")
                        .HasColumnType("jsonb")
                        .HasColumnName("environment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_experiments");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_experiments_created_at");

                    b.ToTable("experiments", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Text.ExtractionResultRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attempts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attempts");

                    b.Property<int>("ClassifyMs")
                        .HasColumnType("integer")
                        .HasColumnName("classify_ms");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("FallbackReason")
                        .HasColumnType("text")
                        .HasColumnName("fallback_reason");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("fallback_used");

                    b.Property<string>("Fields")
                        .HasColumnType("jsonb")
                        .HasColumnName("fields");

                    b.Property<string>("FinalSource")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("final_source");

                    b.Property<string>("Issues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issues");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("LlmElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("llm_elapsed_ms");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("ReadingText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading_text");

                    b.Property<bool?>("ValidationPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("validation_passed");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_count");

                    b.HasKey("Id")
                        .HasName("pk_extraction_results");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_extraction_results_job_id");

                    b.HasIndex("Model", "DocumentType")
                        .HasDatabaseName("ix_extraction_results_model_document_type");

                    b.ToTable("extraction_results", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Text.OcrResultRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AvgConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("engine");

                    b.Property<int>("EngineElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("engine_elapsed_ms");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer")
                        .HasColumnName("line_count");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_version");

                    b.Property<int>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.Property<int>("RequestElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("request_elapsed_ms");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_ocr_results");

                    b.HasIndex("JobId", "Page")
                        .IsUnique()
                        .HasDatabaseName("ix_ocr_results_job_id_page");

                    b.ToTable("ocr_results", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Text.Settings.PipelineSettingsRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pipeline_settings");

                    b.ToTable("pipeline_settings", (string)null);
                });

            modelBuilder.Entity("Api.Shared.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ComboIndex")
                        .HasColumnType("integer")
                        .HasColumnName("combo_index");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("job_type");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("text")
                        .HasColumnName("status_message");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_jobs_created_at");

                    b.HasIndex("ExperimentId")
                        .HasDatabaseName("ix_jobs_experiment_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jobs_status");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Image.ImageResultRecord", b =>
                {
                    b.HasOne("Api.Shared.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_results_jobs_job_id");
                });

            modelBuilder.Entity("Api.Modules.Text.ExtractionResultRecord", b =>
                {
                    b.HasOne("Api.Shared.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_results_jobs_job_id");
                });

            modelBuilder.Entity("Api.Modules.Text.OcrResultRecord", b =>
                {
                    b.HasOne("Api.Shared.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ocr_results_jobs_job_id");
                });
#pragma warning restore 612, 618
        }
    }
}
