// <auto-generated />
using Digitizer.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Digitizer.App.Data.Migrations
{
    [DbContext(typeof(DigitizerDb))]
    partial class DigitizerDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Digitizer.App.Data.CorrectionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectedValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtractedValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExtractionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExtractionId");

                    b.ToTable("corrections", (string)null);
                });

            modelBuilder.Entity("Digitizer.App.Data.DocumentRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastExportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PurgedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TypeWarning")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastExportId");

                    b.HasIndex("Status");

                    b.HasIndex("PackId", "Sha256");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Digitizer.App.Data.ExportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("exports", (string)null);
                });

            modelBuilder.Entity("Digitizer.App.Data.ExtractionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attempts")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FallbackReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fields")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issues")
                        .HasColumnType("TEXT");

                    b.Property<long>("LlmMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("OcrConfidence")
                        .HasColumnType("REAL");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .HasColumnType("TEXT");

                    b.Property<long>("TextMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("extractions", (string)null);
                });

            modelBuilder.Entity("Digitizer.App.Data.CorrectionRecord", b =>
                {
                    b.HasOne("Digitizer.App.Data.DocumentRecord", null)
                        .WithMany("Corrections")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digitizer.App.Data.ExtractionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digitizer.App.Data.DocumentRecord", b =>
                {
                    b.HasOne("Digitizer.App.Data.ExportRecord", null)
                        .WithMany()
                        .HasForeignKey("LastExportId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Digitizer.App.Data.ExtractionRecord", b =>
                {
                    b.HasOne("Digitizer.App.Data.DocumentRecord", null)
                        .WithMany("Extractions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digitizer.App.Data.DocumentRecord", b =>
                {
                    b.Navigation("Corrections");

                    b.Navigation("Extractions");
                });
#pragma warning restore 612, 618
        }
    }
}
